networks:
  backbone:
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:
  backend:
    volumes:
      - ./backend:/app
    build: 
      context: ./backend
      dockerfile: ./backend.dockerfile
    container_name: backend
    ports:
      - "4000:4000"
      - "4242:4242"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    networks:
      - backbone

  
  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - ./database:/app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 172.22.0.10
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./pgadmin:/pgadm
    restart: unless-stopped
    networks:
      - backbone
    env_file:
      - ./.env
    ports:
      - "5433:80"
    

        
