volumes:
  database:
    /home/$USER/database

networks:
  backbone:
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:
  backend:
    volumes: 
    - ./backend:/app
    build: 
      context: ./backend
      dockerfile: ./backend.dockerfile
    container_name: backend
    ports:
      - "4000:4000"
      - "4242:4242"
    env_file:
      - ./backend/.env_file
    restart: unless-stopped
    networks:
      - backbone
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      backbone:
        ipv4_address: 172.22.0.10

        
